Лабораторная iomanip. Лобанова Анна МП-40
LobanovaA/cxx-tasks pull request #1
Opened 2018-11-06 21:38 UTC by LobanovaA

```
1>------ Build started: Project: RUN_TESTS, Configuration: Debug Win32 ------
1>  Test project C:/Users/╨Р╨╜╨╜╨░/Desktop/cxx-tasks/build
1>      Start 1: tests_iomanip:iomanip::simple
1>  1/3 Test #1: tests_iomanip:iomanip::simple .........   Passed    0.10 sec
1>      Start 2: tests_iomanip:iomanip::one_operand
1>  2/3 Test #2: tests_iomanip:iomanip::one_operand ....   Passed    0.06 sec
1>      Start 3: tests_iomanip:iomanip::two_operands
1>  3/3 Test #3: tests_iomanip:iomanip::two_operands ...   Passed    0.06 sec
1>
1>  100% tests passed, 0 tests failed out of 3
1>
1>  Label Time Summary:
1>  tests_iomanip    =   0.22 sec*proc (3 tests)
1>
1>  Total Test time (real) =   0.24 sec
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```

2018-11-07 05:18 UTC, igsha requested changes
Необходимо доработать один несложный пункт. И желательно отрибейзить свой мастер от оригинального cxx-tasks, так как там появились некоторые доработки в тестах. Конкретно этого задания эти доработки не касаются.

2018-11-07 05:18 UTC, igsha commented on iomanip/include/iomanip.hpp
> +	std::ostream & operator<<(int const input)
Сделайте так, чтобы можно было выводить выражения любого типа в поток:
```cpp
std::cout << squares << -3356.89 << squares << "lalala";
```

2018-11-09 08:02 UTC, LobanovaA commented on iomanip/include/iomanip.hpp
> +	std::ostream & operator<<(int const input)
template<typename Insert>
std::ostream & operator<<(Insert const& input)

2018-11-11 06:52 UTC, igsha commented on iomanip/include/iomanip.hpp
> +	std::ostream & operator<<(int const input)
да, так

2018-11-11 06:52 UTC, igsha commented
@LobanovaA, ну а код-то тоже надо поправить

2018-11-11 09:55 UTC, LobanovaA commented
@igsha, замечания исправлены

2018-11-11 11:36 UTC, igsha commented
Вообще рибейз не так делается (неудобно проверяющему смотреть), но это не виляет на результат.

2018-11-11 11:36 UTC, igsha approved these changes

2018-11-11 11:39 UTC, igsha commented
Оценка будет за первую лабу (8 неделя) на 11 неделе => -3 балла.

2018-11-11 11:39 UTC, merged