Proxy
LobanovaA/cxx-tasks pull request #2
Opened 2018-11-11 10:57 UTC by LobanovaA

```
Test project C:/Work/cxx-tasks/build
    Start 1: tests_proxy:proxy::access
1/3 Test #1: tests_proxy:proxy::access ........   Passed    0.11 sec
    Start 2: tests_proxy:proxy::threadsafe
2/3 Test #2: tests_proxy:proxy::threadsafe ....   Passed    1.05 sec
    Start 3: tests_proxy:proxy::primitive
3/3 Test #3: tests_proxy:proxy::primitive .....   Passed    0.04 sec

100% tests passed, 0 tests failed out of 3

Label Time Summary:
tests_proxy    =   1.20 sec*proc (3 tests)

Total Test time (real) =   1.23 sec
```

2018-11-11 11:47 UTC, igsha requested changes
Требуются доработки. Так как лабораторная сдаётся на 11 неделе вместо 9-ой, максимальная оценка снижена на 2 балла.

2018-11-11 11:47 UTC, igsha commented on proxy/include/proxy.hpp
> +        return proxy(ptr_, std::ref(mutex_));
не очень понятно зачему тут `std::ref`. Просто так передать `mutex_` нельзя?

2018-11-11 11:47 UTC, igsha commented on proxy/include/proxy.hpp
> +    class proxy
Попробуйте воспользоваться подсказкой: отнаследоваться приватно от какого-нибудь локера (`std::lock_guard`, `std::unique_lock`). Главное услование: в приватной части класса не должно быть полей, кроме `ptr_`, а также не должно быть явного деструктора.

2018-11-11 11:48 UTC, igsha commented
@LobanovaA, необходимо сделать рибейз от своего мастера, так как одни и те же изменения попали в ветки напрямую, а не через мастер.

2018-11-19 19:21 UTC, LobanovaA commented
@igsha, замечания исправлены

2018-11-19 19:28 UTC, igsha approved these changes

2018-11-19 19:28 UTC, merged