Лабораторная работа. Лобанова Анна МП-40
LobanovaA/cxx-tasks pull request #3
Opened 2018-11-19 19:50 UTC by LobanovaA

```
Test project C:/Work/cxx-tasks/build
    Start 1: tests_type_map:type_map::int
1/3 Test #1: tests_type_map:type_map::int .....   Passed    0.04 sec
    Start 2: tests_type_map:type_map::enum
2/3 Test #2: tests_type_map:type_map::enum ....   Passed    0.03 sec
    Start 3: tests_type_map:type_map::write
3/3 Test #3: tests_type_map:type_map::write ...   Passed    0.03 sec

100% tests passed, 0 tests failed out of 3

Label Time Summary:
tests_type_map    =   0.09 sec*proc (3 tests)
```

2018-11-20 13:09 UTC, igsha requested changes
Требуются доработки. Так как работ больше нет, считаю это за 3 лабараторную. 3 лабараторная была на 10-ой неделе, сейча 13-ая, поэтому максимальная оценка снижена на 3 балла.

2018-11-20 13:09 UTC, igsha commented on type_map/include/type_map.hpp
> +    U& as()
Необходимо ещё добавить const-версию этого метода

2018-11-20 13:09 UTC, igsha commented on type_map/include/type_map.hpp
> +        return (*this)[detail::type_to_index<T, types>().v];
Как можно здесь написать, не создавая объекта `detail::type_to_index`?

2018-11-25 10:20 UTC, LobanovaA commented
@igsha, первое замечание исправила, со вторым не знаю, как решать

2018-11-25 10:58 UTC, igsha commented on type_map/include/type_map.hpp
> +        return (*this)[detail::type_to_index<T, types>().v];
@LobanovaA, просто надо обратиться к этой переменной, она же статическая для всего класса.
```cpp
detail::type_to_index<T, types>::v
```

2018-12-02 15:39 UTC, LobanovaA commented
@igsha, замечания исправила

2018-12-02 19:51 UTC, igsha approved these changes

2018-12-02 19:51 UTC, merged