Лабораторная работа. Лобанова Анна МП40
LobanovaA/cxx-tasks pull request #4
Opened 2018-11-25 11:57 UTC by LobanovaA

2018-11-25 13:29 UTC, igsha requested changes
Лабораторную работу невозможно даже скомпилировать.  
Я так полагаю, здесь 2 лабораторных. Они пойдут в порядке очереди: за 4-ю и 5-ю. Соответственно, просрок по неделям даёт -2 и -1 балл.

2018-11-25 13:29 UTC, igsha commented on parser/include/variant_decorator.hpp
> +struct variant_decorator: public x3::variant<U...>
у этого класса не хватает закрывающей скобки

2018-11-25 13:29 UTC, igsha commented on parser/include/quoted_string.hpp
> +    const auto quated_string = x3::lexeme['"' >> *(~x3::char_('"') | '\\' >> x3::char_ ) >> '"'];
здесь опечатка? В тестах используется другое имя

2018-11-25 13:29 UTC, igsha commented on parser/include/quoted_string.hpp
> +    const auto quated_string = x3::lexeme['"' >> *(~x3::char_('"') | '\\' >> x3::char_ ) >> '"'];
идея верная, но тест всё= не проходит

2018-11-25 13:29 UTC, igsha commented on parser/include/json.hpp
> +                             = = quoted_string >> ':' >> value;
Что значит `= =`?

2018-11-25 13:29 UTC, igsha commented on parser/include/json.hpp
> +        const auto array = x3::rule<struct array, types::json::array>{}
как это может скомпилироваться, если `value` ещё не определён?

2018-11-25 13:29 UTC, igsha commented on parser/include/csv.hpp
> +        const auto string = +(~x3::char_(',') | ~char_('\n'));
не компилируется

2018-12-02 20:23 UTC, LobanovaA commented
@igsha, часть csv исправлена

2018-12-03 05:13 UTC, igsha requested changes
Необходимы доработки.

2018-12-03 05:13 UTC, igsha commented on parser/include/csv.hpp
> +        types::csv::csv operator "" _csv(const char* s, size_t size)
```
parser/include/csv.hpp:71:64: error: unused parameter ‘size’ [-Werror=unused-parameter]
         types::csv::csv operator "" _csv(const char* s, size_t size)
                                                         ~~~~~~~^~~~
```
`size` вообще-то нужный параметр, так как `s` может не иметь нулевого символа в конце строки. Необходимо создавать объект `std::string` из всей имеющейся информации: `std::string(s, size)`

2018-12-03 05:13 UTC, igsha commented on parser/include/quoted_string.hpp
> +    const auto quoted_string = x3::lexeme['"' >> *(~x3::char_('"') | '\\' >> x3::char_ ) >> '"'];
этот тест стал обязательным
```
/tmp/cxx-tasks/parser/tests/quoted_string.cpp:32: FAILED:
due to unexpected exception with message:
  Trailing symbols, difference: 8
```
Здесь неправильный порядок парсинга.

2018-12-28 11:43 UTC, LobanovaA commented
@igsha, все исправления вроде сделаны

2018-12-28 20:10 UTC, igsha commented
![screenshot-2018-12-28t22 52 04](https://user-images.githubusercontent.com/5345170/50526474-60455d00-0af3-11e9-9ad4-6b02fabd4aab.png)
@LobanovaA, а какова роль Yuri Bogomolov в Ваших коммитах?

2018-12-28 20:34 UTC, LobanovaA commented
@igsha, в этой лабораторной используется boost, который я не могла установить под windows. Именно поэтому первоначальный комит был сырой(даже не компилировался). Чтобы внести правки я попросила Yuri Bogomolov его ноутбук на время, но в настройках git видимо был его логин

2018-12-29 06:00 UTC, igsha commented
Хмм... судя по тому, что это коммитер неправильный, а не автор, очень похоже на правду. Ок.

2018-12-29 06:00 UTC, igsha approved these changes

2018-12-29 06:00 UTC, merged