Лобораторная работа iterator. Лобанова Анна МП40
LobanovaA/cxx-tasks pull request #5
Opened 2018-12-02 15:31 UTC by LobanovaA

Test project /home/ybogomolov/MP/Anna/build
    Start 1: tests_iterator:iterator::operations
1/4 Test #1: tests_iterator:iterator::operations .........   Passed    0.00 sec
    Start 2: tests_iterator:iterator::write
2/4 Test #2: tests_iterator:iterator::write ..............   Passed    0.00 sec
    Start 3: tests_iterator:iterator::copy_from_vector
3/4 Test #3: tests_iterator:iterator::copy_from_vector ...   Passed    0.00 sec
    Start 4: tests_iterator:iterator::copy_to_vector
4/4 Test #4: tests_iterator:iterator::copy_to_vector .....   Passed    0.00 sec

2018-12-02 19:50 UTC, igsha requested changes
Требуются небольшие оптимизации. Засчитаю как 6-ю лабораторную.
-1 балл за просрок

2018-12-02 19:50 UTC, igsha commented on iterator/include/iterator.hpp
> +        advance(-1);
Попробуйте развернуть `increment` и `decrement`, так как можно соптимизировать вызов `advance`

2018-12-09 19:58 UTC, LobanovaA commented on iterator/include/iterator.hpp
> +        advance(-1);
@igsha, т.е. нужно написать эти методы без использования advance?

2018-12-09 20:02 UTC, igsha commented on iterator/include/iterator.hpp
> +        advance(-1);
@LobanovaA, ага, без использования `advance`. Они будут похожи на `advance`, но некоторые `if`-ы уйдут, поэтому они будут более оптимальными.

2019-01-16 18:26 UTC, LobanovaA commented
@igsha, проверьте пожалуйста исправления

2019-01-16 18:45 UTC, igsha approved these changes
Немного неправильно отрибейзились (появился левый коммит в мастере). Но на саму лабораторную это напрямую не влияет. Не собирается только.

2019-01-16 18:45 UTC, igsha commented on iterator/include/iterator.hpp
> +            index += width_- index % (int)stride_ + 1;
Тут, наверное, минус должен быть. Но допустим, я этого не видел

2019-01-16 18:45 UTC, merged