Bdz
LobanovaA/cxx-tasks pull request #7
Opened 2019-01-16 19:21 UTC by LobanovaA

2019-01-16 20:12 UTC, igsha requested changes
11 правильных. Можете подумать над оставшимся вопрос.
В мёрже присутствуют обратные петли, поэтому смёржить код не получается. Необходимо правильно сделать рибейз от мастера: `git rebase -i master` и удаляем (drop) все непонятные коммиты, которых нет в мастере и которые не были сделаны в этой текущей ветке.

2019-01-16 20:12 UTC, igsha commented on parser/include/variant_decorator.hpp
> +//! Базовых конструкторов и операторов присваивания достаточно, так как variant_decorator является декоратором, т.е. предоставляет новые методы работы с объектом базового класса
Но, судя по коду, не достаточно. Здесь вопрос про **собственные** конструкторы, т.е. те, которые определены не через `using`. И таковые в коде имеются. Зачем они?

2019-01-18 21:35 UTC, LobanovaA commented
@igsha, ответ на вопрос исправила и сделала ребейз

2019-01-19 11:11 UTC, igsha approved these changes

2019-01-19 11:11 UTC, merged